[package]
name = "dagal"
version = "0.1.0"
edition = "2021"
authors = ["Danny Le <git@dannydoes.graphics>"]

[dependencies]
ash = "0.38.0"
ash-window = {version = "0.13.0", optional = false}
gpu-allocator = { version = "0.26.0", features = ["default", "vulkan"], optional = true }
winit = {version = "0.30.0", optional = true}
raw-window-handle = {version = "0.6.1", optional = false}
vk-mem = {git = "https://github.com/gwihlidal/vk-mem-rs.git", rev = "56228c9", optional = true }
derivative = "2.2.0"
anyhow = "1.0.82"
thiserror = "1.0.59"
tracing = "0.1.40"


[dev-dependencies]
winit = {version = "0.30.0", optional = false}

[features]
default = ["bootstrap", "winit", "gpu-allocator", "vk-mem-rs", "log-lifetimes", "log-memory-allocations"]
# Adds support for winit into dagal
winit = ["dep:winit"]
# Adds support for gpu-allocator for the primary allocation
gpu-allocator = ["dep:gpu-allocator"]
# Adds support for vk-mem-rs for the primary allocation
vk-mem-rs = ["dep:vk-mem"]
# Whether to log the lifetime of objects
log-lifetimes = []
# Whether to log memory allocation lifetimes
log-memory-allocations = []
# Whether the bootstrap module should be enabled
bootstrap = []
# Whether resources should be automatically cleaned up
raii = []
